export const GITHUB_OAUTH_PROVIDER = "github";
export const ALLOWED_OAUTH_PROVIDERS = [GITHUB_OAUTH_PROVIDER];

export const TOKENS_LIMIT = 10000;
export const PORTFOLIO_GENERATION_PROMPT_TEMPERATURE = 0.3;
