name: Setup Environment
description: Checkout code and setup Node.js with pnpm cache

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

